/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-07-03 09:21:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
 request.setCharacterEncoding("UTF-8");
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"UTF-8\">\r\n");
      out.write("		<title>Insert title here</title>\r\n");
      out.write("		<link rel=\"stylesheet\" type=\"text/css\" href=\"css/common.css\">\r\n");
      out.write("		<link rel=\"stylesheet\" type=\"text/css\" href=\"css/menu.css\">\r\n");
      out.write("		<link rel=\"stylesheet\" type=\"text/css\" href=\"css/index.css\">\r\n");
      out.write("		<link rel=\"stylesheet\" type=\"text/css\" href=\"css/mainPage/slideShow.css\">\r\n");
      out.write("		<link rel=\"stylesheet\" type=\"text/css\" href=\"css/mainPage/poster.css\">\r\n");
      out.write("		<link rel=\"stylesheet\" type=\"text/css\" href=\"css/mainPage/notice.css\">\r\n");
      out.write("		<link rel=\"stylesheet\" type=\"text/css\" href=\"css/mainPage/community.css\">\r\n");
      out.write("		<link rel=\"stylesheet\" type=\"text/css\" href=\"css/mainPage/feed.css\">\r\n");
      out.write("		<script src=\"js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("		<script src=\"js/mainPage/subMenu.js\"></script>\r\n");
      out.write("		<script src=\"js/mainPage/slideShow.js\"></script>\r\n");
      out.write("	</head>\r\n");
      out.write("	<body>\r\n");
      out.write("	<div id=\"wrap\">\r\n");
      out.write("	<header>\r\n");
      out.write("		<div id=\"top-headBox\">\r\n");
      out.write("			<div id=\"top-headLogo\">\r\n");
      out.write("			<h3>로고</h3>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"top-headSearchBar\">\r\n");
      out.write("				<form>\r\n");
      out.write("					<input type=\"text\" name=\"mainSearch\" value=\"search...\">\r\n");
      out.write("					<input type=\"submit\" name=\"mainSearchBtn\" value=\"검색\">\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"top-headLoginSignUp\">\r\n");
      out.write("			<a href=\"#\">회원가입 </a>/\r\n");
      out.write("			<a href=\"#\">로그인 &nbsp;</a>\r\n");
      out.write("			</div>\r\n");
      out.write("	 	</div>\r\n");
      out.write("	</header>\r\n");
      out.write("	 <nav>\r\n");
      out.write("		<div id=\"menuBox\">\r\n");
      out.write("			<div id=\"mainMenuBox\">\r\n");
      out.write("			메인메뉴\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"subMenuBox\">\r\n");
      out.write("			서브메뉴\r\n");
      out.write("			</div>	 \r\n");
      out.write("	 	</div>\r\n");
      out.write("	 </nav>\r\n");
      out.write("	 <section>\r\n");
      out.write("	 	<article id=\"slideShow\">\r\n");
      out.write("		<div id=\"slideBox\">\r\n");
      out.write("			<div id=\"slidePanel\">\r\n");
      out.write("			<div>1</div>\r\n");
      out.write("			<div>2</div>\r\n");
      out.write("			<div>3</div>\r\n");
      out.write("			<div>4</div>\r\n");
      out.write("			<div>5</div>\r\n");
      out.write("			</div> \r\n");
      out.write("	 	</div>\r\n");
      out.write("	 	</article>\r\n");
      out.write("	 	<article id=\"poster\">\r\n");
      out.write("	 		<h2 id=\"posterNameBox\"> 포스터</h2> \r\n");
      out.write("		<div id=\"posterBox\">\r\n");
      out.write("			<div class=\"posterTemp\">1\r\n");
      out.write("				<div class=\"posterImg\"></div>\r\n");
      out.write("				<div class=\"posterExplain\">5</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"posterTemp\">2\r\n");
      out.write("				<div class=\"posterImg\"></div>\r\n");
      out.write("				<div class=\"posterExplain\">6</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"posterTemp\">3\r\n");
      out.write("				<div class=\"posterImg\"></div>\r\n");
      out.write("				<div class=\"posterExplain\">7</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"posterTemp\">4\r\n");
      out.write("				<div class=\"posterImg\"></div>\r\n");
      out.write("				<div class=\"posterExplain\">8</div>\r\n");
      out.write("			</div>\r\n");
      out.write("	 	</div>\r\n");
      out.write("	 	</article>\r\n");
      out.write("	 	<article id=\"notice\">\r\n");
      out.write("			<div id=\"noticeBox\">\r\n");
      out.write("				<div id=\"mainNotice\" class=\"noticeBoxCols\">\r\n");
      out.write("					<h3>&#60;공지사항&#62;</h3>\r\n");
      out.write("					<a href=\"#\">공지사항 공지사항  </a><br>\r\n");
      out.write("					<a href=\"#\">공지사항 공지사항  </a><br>\r\n");
      out.write("					<a href=\"#\">공지사항 공지사항  </a><br>\r\n");
      out.write("					<a href=\"#\">공지사항 공지사항  </a><br>\r\n");
      out.write("					<a href=\"#\">공지사항 공지사항  </a><br>\r\n");
      out.write("				</div>\r\n");
      out.write("					<div id=\"searchRankingNotice\" class=\"noticeBoxCols\">\r\n");
      out.write("					실시간 행사 검색 순위\r\n");
      out.write("				</div>\r\n");
      out.write("					<div id=\"eventNotice\" class=\"noticeBoxCols\">\r\n");
      out.write("					이벤트 칸\r\n");
      out.write("				</div>\r\n");
      out.write("		 	</div>\r\n");
      out.write("	 	</article>\r\n");
      out.write("	 	<article id=\"community\">\r\n");
      out.write("	 		<h2 id=\"communityNameBox\"> 커뮤니티</h2> \r\n");
      out.write("				<div id=\"communityBox\">\r\n");
      out.write("					<div id=\"communityHref\">\r\n");
      out.write("						<div id=\"SNSReview\" class=\"communityBoxCols\">\r\n");
      out.write("						인스타 or 블로그 리뷰\r\n");
      out.write("						</div>\r\n");
      out.write("						<div id=\"accompanyBoard\" class=\"communityBoxCols\">\r\n");
      out.write("						실시간 행사 검색 순위\r\n");
      out.write("						</div>\r\n");
      out.write("						<div id=\"communityBoard\" class=\"communityBoxCols\">\r\n");
      out.write("						이벤트 칸\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div id=\"communitySNSHashTag\">\r\n");
      out.write("						<span>&#35;워터밤</span>\r\n");
      out.write("						<span>&#35;에버랜드</span>\r\n");
      out.write("						<span>&#35;인천_펜타포드_락_페스티벌</span>\r\n");
      out.write("			 		</div>\r\n");
      out.write("			 		<div id=\"communityAmenity\">\r\n");
      out.write("						숙소 연계 이벤트 배너\r\n");
      out.write("			 		</div>\r\n");
      out.write("			 		<div id=\"communityAd\">\r\n");
      out.write("						커뮤니티 광고 이미지\r\n");
      out.write("			 		</div>\r\n");
      out.write("			 		<div id=\"communityAllianceCard\">\r\n");
      out.write("						카드사 제휴\r\n");
      out.write("			 		</div>\r\n");
      out.write("			 		<div id=\"communityPublic\">\r\n");
      out.write("						<div class=\"communityPublicCols\">\r\n");
      out.write("						배너1\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"communityPublicCols\">\r\n");
      out.write("						배너2\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"communityPublicCols\">\r\n");
      out.write("						배너3\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"communityPublicCols\">\r\n");
      out.write("						배너4\r\n");
      out.write("						</div>\r\n");
      out.write("			 		</div>\r\n");
      out.write("			 	</div>\r\n");
      out.write("			 	\r\n");
      out.write("	 	</article>\r\n");
      out.write("	 	<!-- <article id=\"feed\">\r\n");
      out.write("	 		<h2 id=\"feedNameBox\"> 피드</h2> \r\n");
      out.write("		<div id=\"feedBox\">\r\n");
      out.write("			<div>1</div>\r\n");
      out.write("			<div>2</div>\r\n");
      out.write("			<div>3</div>\r\n");
      out.write("			<div>4</div>\r\n");
      out.write("			<div>5</div>\r\n");
      out.write("			<div>6</div>\r\n");
      out.write("	 	</div>\r\n");
      out.write("	 	</article> -->\r\n");
      out.write("	 </section>\r\n");
      out.write("	 <footer id=\"bottomBox\">\r\n");
      out.write("	 	<div id=\"ent-info\">\r\n");
      out.write("			<div>\r\n");
      out.write("			기업정보\r\n");
      out.write("			</div> \r\n");
      out.write("	 	</div>\r\n");
      out.write("	 </footer>\r\n");
      out.write("	</div>\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
